const  admincontroller = require(`${path}/Controllers/AdminController`)
module.exports = (app) => {
    app.route('/')
    .get(admincontroller.Home)
    app.route('/check-in')
    .get(admincontroller.CheckIn)
    .post(admincontroller.pCheckIn)
    app.route('/thu-moi')
    .get(admincontroller.ThuMoi)
    app.route('/bieu-quyet/:id')
    .get(admincontroller.BieuQuyet)
    .post(admincontroller.pBieuQuyet)
    app.route('/bat-dau-dai-hoi')
    .get(admincontroller.DownloadFileDieuKien)
    app.route('/bau-cu')
    .get(admincontroller.vBauCu)
    app.route('/ung-vien/:id')
    .get(admincontroller.fBauCu)
    .post(admincontroller.pBauCu)
    
    // AJAX
    app.route('/ajax/ma-co-dong')
    .get(admincontroller.getMaCoDong)
    app.route('/ajax/ma-uy-quyen')
    .get(admincontroller.getMaUyQuyen)
    app.route('/ajax/chot-cau-hoi')
    .get(admincontroller.ChotCauHoi)
    app.route('/ajax/refresh/tan-thanh/:id')
    .get(admincontroller.refreshTanThanh)
    app.route('/ajax/refresh/khong-tan-thanh/:id')
    .get(admincontroller.refreshKhongTanThanh)
    app.route('/ajax/thong-ke')
    .get(admincontroller.ThongKe)
    app.route('/ajax/chot-van-de')
    .get(admincontroller.DownloadFileBieuQuyet)
    app.route('/ajax/danh-sach-ung-vien')
    .get(admincontroller.DanhSachUngVien)
    app.route('/ajax/thong-tin-dai-bieu')
    .get(admincontroller.ThongTinDaiBieu)
    // Test case
    app.route('/test')
    .get((req,res) => {
        res.render('slides/bieu-quyet')
    })
    app.route('/mc-script')
    .get((req,res)=>{
        res.render('admin/mc-script')
    })
    app.route('/slide-show')
    .get(admincontroller.SlideShow)
    app.route('/slide-bieu-quyet')
    .get(admincontroller.liveBieuQuyet)
    
}